/**
* Generated by @proofgeist/fmdapi package
* 2022-07-01 08:11 am -05:00
* https://github.com/proofgeist/fmdapi
* DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
*/

import { z } from "zod";
import { DataApi } from "@proofgeist/fmdapi";
export const ZProjects = z.object({
    "emailAll": z.string(),
    "name": z.string(),
    "JSONWeb": z.string(),
    "eddID": z.union([z.string(), z.number()]),
    "emailPrimary": z.string()
});
export type TProjects = z.infer<typeof ZProjects>;
if (!process.env.OTHER_NAME)
    throw new Error("Missing env var: OTHER_NAME");
if (!process.env.OTHER_SERVER_NAME)
    throw new Error("Missing env var: OTHER_SERVER_NAME");
if (!process.env.OTHER_API_KEY)
    throw new Error("Missing env var: OTHER_API_KEY");
export const client = DataApi<any, TProjects>({
    auth: { apiKey: process.env.OTHER_API_KEY },
    db: process.env.OTHER_NAME,
    server: process.env.OTHER_SERVER_NAME,
    layout: "edd_customer_web"
}, {
    fieldData: ZProjects
});
