// Autogenerated by @fig/complete-commander
const completionSpec: Fig.Spec = {
  name: "codegen",
  subcommands: [
    {
      name: "help",
      description: "Display help for command",
      priority: 49,
      args: { name: "command", isOptional: true, template: "help" },
    },
  ],
  options: [
    {
      name: "--init",
      description: "Add the configuration file to your project",
    },
    {
      name: "--config",
      description: "Optional config file name",
      args: { name: "filename" },
    },
    {
      name: "--env-path",
      description: "Optional path to your .env file",
      args: { name: "path", default: ".env.local" },
    },
    {
      name: "--skip-env-check",
      description: "Ignore loading environment variables from a file",
    },
    {
      name: ["-h", "--help"],
      description: "Display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
