
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const Ztest = z.object({
      "related::related_field": z.string(),
      "related::recordId": z.union([z.string(), z.number()]),
  });

  export type Ttest = z.infer<typeof Ztest>;

  export const ZVLYesNo = z.enum(["Yes", "No"]);

  export type TVLYesNo = z.infer<typeof ZVLYesNo>;

  export const ZtestLayout = z.object({
      "anything": z.string(),
      "recordId": z.union([z.string(), z.number()]),
      "fieldWithValues": z.enum(["Yes", "No", ""]).catch(""),
  });

  export type TtestLayout = z.infer<typeof ZtestLayout>;

  export const ZtestLayoutPortals = z.object({
      "test": Ztest
  });

  export type TtestLayoutPortals = z.infer<typeof ZtestLayoutPortals>;
