/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */
import { z } from "zod";

// @generated
// prettier-ignore
/* eslint-disable */
export const Zlong_and_strangeportalNameforTesting = z.object({
      "long_and_strange.portalName#forTesting::PrimaryKey": z.string(),
      "long_and_strange.portalName#forTesting::CreationTimestamp": z.string(),
      "long_and_strange.portalName#forTesting::CreatedBy": z.string(),
      "long_and_strange.portalName#forTesting::ModificationTimestamp": z.string(),
      "long_and_strange.portalName#forTesting::ModifiedBy": z.string(),
      "long_and_strange.portalName#forTesting::related_field": z.string(),
      "long_and_strange.portalName#forTesting::recordId": z.union([z.string(), z.number()]),
  });

export type Tlong_and_strangeportalNameforTesting = z.infer<
  typeof Zlong_and_strangeportalNameforTesting
>;

export const ZweirdPortals = z.object({});

export type TweirdPortals = z.infer<typeof ZweirdPortals>;

export const ZweirdPortalsPortals = z.object({
  "long_and_strange.portalName#forTesting":
    Zlong_and_strangeportalNameforTesting,
});

export type TweirdPortalsPortals = z.infer<typeof ZweirdPortalsPortals>;
