/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */

// @generated
// prettier-ignore
/* eslint-disable */
import { z } from "zod";
export const ZtestLayout = z.object({
  anything: z.string(),
  recordId: z.union([z.string(), z.number()]),
  values: z.enum(['value1', 'value2', 'value3', '']).catch(''),
});
export type TtestLayout = z.infer<typeof ZtestLayout>;
export const Ztest = z.object({
  'related::related_field': z.string(),
  'related::recordId': z.union([z.string(), z.number()]),
});
export type Ttest = z.infer<typeof Ztest>;
export const ZtestLayoutPortals = z.object({
  test: Ztest,
});
export type TtestLayoutPortals = z.infer<typeof ZtestLayoutPortals>;
