/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */
import { DataApi, FetchAdapter } from "@proofgeist/fmdapi";
import {
  TtestLayout,
  ZtestLayout,
  TtestLayoutPortals,
  ZtestLayoutPortals,
} from "../testLayout";
import { upstashTokenStore } from "../../../src/tokenStore";

// @generated
// prettier-ignore
/* eslint-disable */
if (!process.env.FM_DATABASE) throw new Error("Missing env var: FM_DATABASE");
if (!process.env.FM_SERVER) throw new Error("Missing env var: FM_SERVER");
if (!process.env.FM_USERNAME) throw new Error("Missing env var: FM_USERNAME");
if (!process.env.FM_PASSWORD) throw new Error("Missing env var: FM_PASSWORD");

export const client = DataApi<any, TtestLayout, TtestLayoutPortals>({
  adapter: new FetchAdapter({
    auth: {
      username: process.env.FM_USERNAME,
      password: process.env.FM_PASSWORD,
    },
    db: process.env.FM_DATABASE,
    server: process.env.FM_SERVER,
    tokenStore: upstashTokenStore({ token: "", url: "" }),
  }),
  layout: "layout",
  zodValidators: { fieldData: ZtestLayout, portalData: ZtestLayoutPortals },
});
