
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { DataApi, OttoAdapter, type OttoAPIKey } from "@proofgeist/fmdapi";
  import { type TweirdPortals, ZweirdPortals, type TweirdPortalsPortals, ZweirdPortalsPortals } from "../weirdPortals";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  if (!process.env.DIFFERENT_FM_DATABASE) throw new Error("Missing env var: DIFFERENT_FM_DATABASE")
  if (!process.env.DIFFERENT_FM_SERVER) throw new Error("Missing env var: DIFFERENT_FM_SERVER")
  if (!process.env.DIFFERENT_OTTO_API_KEY) throw new Error("Missing env var: DIFFERENT_OTTO_API_KEY")

  export const client = DataApi<any, TweirdPortals, TweirdPortalsPortals>({
      adapter: new OttoAdapter({
          auth: { apiKey: process.env.DIFFERENT_OTTO_API_KEY as OttoAPIKey },
          db: process.env.DIFFERENT_FM_DATABASE,
          server: process.env.DIFFERENT_FM_SERVER,
      }),
      layout: "Weird Portals",
      zodValidators: { fieldData: ZweirdPortals, portalData: ZweirdPortalsPortals },
  });
