/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */

// @generated
// prettier-ignore
/* eslint-disable */
import { TtestLayout, TtestLayoutPortals, ZtestLayout, ZtestLayoutPortals } from "../testLayout";
import {
  DataApi,
  OttoAdapter,
  OttoAPIKey,
  FetchAdapter,
} from '@proofgeist/fmdapi';
import { WebViewerAdapter } from '@proofgeist/fm-webviewer-fetch/adapter';
if (!process.env.FM_DATABASE) throw new Error('Missing env var: FM_DATABASE');
if (!process.env.FM_SERVER) throw new Error('Missing env var: FM_SERVER');
if (!process.env.OTTO_API_KEY) throw new Error('Missing env var: OTTO_API_KEY');
export const client = DataApi<any, TtestLayout, TtestLayoutPortals>({
  adapter: new OttoAdapter({
    auth: { apiKey: process.env.OTTO_API_KEY as OttoAPIKey },
    db: process.env.FM_DATABASE,
    server: process.env.FM_SERVER,
  }),
  layout: 'layout',
  zodValidators: { fieldData: ZtestLayout, portalData: ZtestLayoutPortals },
});
