export const commentHeader = `
/**
* Generated by @proofgeist/fmdapi package
* https://github.com/proofgeist/fmdapi
* DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
*/

// @generated
// prettier-ignore
/* eslint-disable */

`;

export const varname = (name: string) => name.replace(/[^a-zA-Z0-9_]/g, "");
